### ISSUE TITLE
Create function that unconditionally raises an error

### ISSUE THREAD

**Issue by krlmlr** [hannes/duckdb-rfuns#102]
Sometimes, we want to check that materialization does not occur in duckplyr. A function with no parameters that throws an exception could help us with that. Need to double-check if it actually does.

**Comment by romainfrancois** [comment]
Would that be an aggregate function i.e. similar to `sum` using `AggregateFunctionSet` or a scalar function, using `ScalarFunctionSet` ?

**Comment by krlmlr** [comment]
Same as `random()` perhaps?

https://duckdb.org/docs/sql/functions/numeric.html

**Comment by krlmlr** [comment]
No longer needed after https://github.com/duckdb/duckdb-r/pull/526.
