### ISSUE TITLE
Comparison between dates, times and strings, ...

### ISSUE THREAD

**Issue by romainfrancois** [hannes/duckdb-rfuns#52]
Follow up from; https://github.com/hannes/duckdb-rfuns/pull/33#discussion_r1498806449

**Comment by romainfrancois** [comment]
comparing dates to dates, or times to times is fine: 

``` r
duckdbrfuns:::spaceship(Sys.Date(), Sys.Date())
#>                x          y   ==    !=     <   <=     >   >=
#> rfuns 2024-03-25 2024-03-25 TRUE FALSE FALSE TRUE FALSE TRUE
#> r     2024-03-25 2024-03-25 TRUE FALSE FALSE TRUE FALSE TRUE
duckdbrfuns:::spaceship(as.POSIXct(Sys.Date()), as.POSIXct(Sys.Date()))
#>                x          y   ==    !=     <   <=     >   >=
#> rfuns 2024-03-25 2024-03-25 TRUE FALSE FALSE TRUE FALSE TRUE
#> r     2024-03-25 2024-03-25 TRUE FALSE FALSE TRUE FALSE TRUE
```

but we get different results when comparing dates and times for some reason: 

``` r
duckdbrfuns:::spaceship(Sys.Date(), as.POSIXct(Sys.Date()))
#>                x          y    ==    !=     <   <=     >    >=
#> rfuns 2024-03-25 2024-03-25  TRUE FALSE FALSE TRUE FALSE  TRUE
#> r     2024-03-25 2024-03-25 FALSE  TRUE  TRUE TRUE FALSE FALSE
```

<sup>Created on 2024-03-25 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment]
We can always fall back to R in these weird cases, but this will have to be detected at the binding stage. So, if a function doesn't exist for specific arguments, it will work out fine.

Here, we should just omit the implementation with a comment.

**Comment by romainfrancois** [comment]
Let me know if #66 does not work for you;

**Comment by romainfrancois** [comment]
Can you expand on "this will have to be detected at the binding stage" ?

**Comment by krlmlr** [comment]
- Evaluation stage: calling `rel_to_altrep_df()`
- Binding stage: calling other `rel_*()` functions

**Comment by krlmlr** [comment]
Yes, failing at `rel_to_altrep()` is too late.

Can we supply our own binding logic instead of relying on duckdb for this? We might be able to rebuild a part of the infrastructure that currently does the binding for us, and then upstream if useful

**Comment by romainfrancois** [comment]
I will have another look, but I'm not sure how to make it happen now.

**Comment by hannes** [comment]
You can define a custom binding function for a `ScalarFunction` and then just throw an exception if you don't like the argument types

**Comment by krlmlr** [comment]
IIUC, the `bind_scalar_function_t bind` argument to `ScalarFunction::ScalarFunction()` can help here.

**Comment by romainfrancois** [comment]
> You can define a custom binding function for a `ScalarFunction` and then just throw an exception if you don't like the argument types

That's essentially what we are doing.
