### ISSUE TITLE
Build for msys2 (Rtools)

### ISSUE THREAD

**Issue by krlmlr** [hannes/duckdb-rfuns#53]
Currently fails: https://github.com/duckdblabs/duckplyr/actions/runs/8174092644/job/22348184214?pr=100#step:7:153

> Error: Error: HTTP Error: Failed to download extension "rfuns" at URL "http://duckdb-rfuns.s3.us-east-1.amazonaws.com/v0.9.2/windows_amd64_rtools/rfuns.duckdb_extension.gz"

**Comment by krlmlr** [comment]
We have Windows builds, probably just not for duckdb 0.9.2. This might become a non-issue when duckdb 0.10.0 is out, which is very soon.

**Comment by krlmlr** [comment]
@Antonov548: Can you please check if https://github.com/duckdblabs/duckplyr/pull/100 works for you on Windows native (not WSL)?

**Comment by Antonov548** [comment]
> @Antonov548: Can you please check if [duckdblabs/duckplyr#100](https://github.com/duckdblabs/duckplyr/pull/100) works for you on Windows native (not WSL)?

Not sure what exactly to check. But package is builds and `ext_install` seems works fine.

**Comment by krlmlr** [comment]
With duckdb 0.10.0? Can you test with `testthat::test_local()` ?

**Comment by Antonov548** [comment]
> With duckdb 0.10.0? Can you test with `testthat::test_local()` ?

Yes, it is with duckdb 0.10.0.
One failed test. I guess due to the different warning message.

```bash
── Failed tests ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (test-count-tally.R:183:3): .drop is deprecated
`out <- duckplyr_add_count(df, f, .drop = FALSE)` did not throw the expected warning.

[ FAIL 1 | WARN 0 | SKIP 231 | PASS 1515 ]
Error: Test failures
```

**Comment by krlmlr** [comment]
Thanks!
