### ISSUE TITLE
date <=> time and time <=> date should fail with a binding error

### ISSUE THREAD

**Issue by krlmlr** [hannes/duckdb-rfuns#67]
Is this possible? How to test?

**Comment by romainfrancois** [comment]
We can definitely support that. What should the error be ? For reference, R gives a warning and then goes and do something non sensical 🦐 

``` r
Sys.time() < Sys.Date()
#> Warning: Incompatible methods ("Ops.POSIXt", "Ops.Date") for "<"
#> [1] FALSE
```

<sup>Created on 2024-03-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by romainfrancois** [comment]
That kiond of was the purpose of the `dispatch()` function, to see which variant would be selected. In that case, the `TIMESTAMP <=> TIMESTAMP` ends up selected and duckdb correctly converts a date to a timestamp. 

So we can't "not implement" it, we have to implement one that specifically fails. I'll do this next.

**Comment by krlmlr** [comment]
I think an exception will do fine -- should be caught by duckdb and translated into a binding error.

**Comment by krlmlr** [comment]
For the type of exceptions, take a look at what other duckdb functions throw, and adapt.
