### ISSUE TITLE
Inline extension into duckdb R package

### ISSUE THREAD

**Issue by krlmlr** [hannes/duckdb-rfuns#78]
Should we organize the development in a way that the relevant files from this repo can be copied into the duckdb-r repo and this extension becomes bundled with the R package?

Reasons:

- R (and perhaps even duckplyr) might be the only user ever for this extension
- duckplyr can look at the duckdb version to detect the capabilities of the extension (otherwise we'd need separate versioning for the extension)
- fewer things can go wrong with downloading and installing the extension

What are the downsides?

**Comment by romainfrancois** [comment]
Or does the extension belong in the `duckdb-r` repo so that it's always there ?

**Comment by krlmlr** [comment]
@hannes: Do you see downsides in including the rfuns extension into the R package? Who can help with the technical aspects of bundling the extension into the same shared library?
